### ISSUE TITLE
Inutile model validation error message

### ISSUE THREAD

**Issue by ByteBlast** [TestStack/TestStack.FluentMVCTesting#25]
```C#
[Test]
public void Post_ReturnsCorrectModel()
{
    const string Slug = "abc";
    repository
       .Setup(repo => repo.Find(Slug))
       .Returns(PostsMother.CreatePost(withSlug: Slug));

    controller
        .WithCallTo(c => c.Post(Slug))
        .ShouldRenderDefaultView()
        .WithModel<Post>(actual => actual.Slug == "something random");
}
```
The aforementioned code produces the following error message - 

> Expected view model to pass the given condition, but it failed.

In practice I found this error message to be completely unhelpful. Instead I suggest something along the lines of -

> Expected "abc" but instead was "something random".

**Comment by ByteBlast** [comment]
Since I implemented the basic `ExpressionInspector` and consistently, improved the error messages, I have no longer observed this problem. 

There are still some short-comings when it comes to compiler-generated code (like closure display classes) but personally, I have not found this to be an issue in practice. 

The good news is, if the problem does become prevalent in the future 

1. We have an extensive test suite in place for the `ExpressionInspector` to catch regressions 
2. I have done some research into possible solutions. 

I am happy to close this issue now if you are, Rob?

**Comment by robdmoore** [comment]
Yep :)

Great work on this - stuff like this makes the library way nicer to use!!
