### ISSUE TITLE
Support for MVC 5.2.3

### ISSUE THREAD

**Issue by zombiecodekill** [TestStack/TestStack.FluentMVCTesting#64]
The main FluentMVCTesting is written for MVC v5.2.2. It would be great if this could work for the current version v5.2.3

**Comment by robdmoore** [comment]
It should work for 5.2.3, you just might need some binding redirects.

**Comment by lichunbin814** [comment]
you can upgrade system.web.mvc to 5.2.3 for nuget , and use below code in web.config

```
  <dependentAssembly>
    <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
    <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
  </dependentAssembly>
```
